permalink: /:title
author:
  name:  Okinawa Ruby User Group | Okinawa.rb
  email: admin@ruby.okinawa

baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://ruby.okinawa" # the base hostname & protocol for your site
twitter_username: okinawarb
github_username:  okinawarb
source:      ./
destination: ./_site
timezone: Asia/Tokyo
encoding: utf-8

highlighter: rouge
exclude:
- vendor
- Gemfile
- Gemfile.lock
